#!/bin/bash
cd "$('dirname' '--' "${0}")"
('pdflatex' './main.tex');
('pdflatex' './main.tex');
('pdflatex' './main.tex');
('pdflatex' './main.tex');
('pdflatex' './main.tex');
('pdflatex' './main.tex');
('pdflatex' './main.tex');
('pdflatex' './main.tex');
('pdfcrop' 'main.pdf' './tmp.pdf');
('mypdf2djvu' './tmp.pdf');
('convert' 'tmp.djvu' 'tmp.png');
('pdf2svg' './tmp.pdf' './tmp.svg');
'cp' 'tmp.svg' '/tmp/0.svg'
exit '0'
