#!/bin/bash
cd "$('dirname' '--' "${0}")"
'ls' "./${1}/out.root"&&exit '0'
'ls' "./${1}/LHE.in"&&exit '0'
'cp' './LHEWithISR.in' "${1}/LHE.in"
source '/home/aravind/herwig'
cd "${1}"
'Herwig' 'read' 'LHE.in'
'Herwig' 'run' 'LHE.run'
'../RunDelphesWithISR' "${1}"
'rm' '-vf' '--' 'LHE.hepmc' 'LHE-EvtGen.log' 'LHE.log' 'LHE.out' 'LHE.run' 'LHE.in' 'LHE.tex'
exit '0'
